version: '3'
services:
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: navedex_api
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    env_file:
      - .env
    links:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - navedex_api_data:/var/lib/postgresql/data
volumes:
  navedex_api_data: