default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>


development:
  <<: *default
  database: navedex_api_development

test:
  <<: *default
  database: navedex_api_test

production:
  <<: *default
  database: navedex_api_production
  username: navedex_api
