default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  host: <%= ENV.fetch("POSTGRES_HOST") %>


development:
  <<: *default
  database: navedex_api_development

test:
  <<: *default
  database: navedex_api_test

production:
  <<: *default
  database: navedex_api_production
  username: navedex_api
  password: <%= ENV['NAVEDEX_API_DATABASE_PASSWORD'] %>
